### ISSUE TITLE
Exception thrown by ANR WatchDog not catchable by ACRA

### ISSUE THREAD

**Issue by rssc** [SalomonBrys/ANR-WatchDog#16]
Hi,

I was trying to use ANR WatchDog and ACRA to catch a bug, but when the ANR WatchDog triggers, ACRA doesn't actually catch the exception, but throws an error itself and therefore hands off the exception to the system, which then promptly kills the app. The error seems to be related to ACRA trying to serialize the exception generated by ANR WatchDog (see below).

I am using ACRA 4.8.2, and ANR WatchDog 1.1.*.

Any help would be greatly appreciated. Thanks!

```
03-07 17:52:43.984 18923-18953/ch.ione.safefingerprint E/ACRA: ACRA caught a ANRError for ch.ione.safefingerprint
                                                               com.github.anrwatchdog.ANRError: Application Not Responding
                                                               Caused by: com.github.anrwatchdog.ANRError$$$_Thread: main
                                                                   at android.os.BinderProxy.transactNative(Native Method)
                                                                   at android.os.BinderProxy.transact(Binder.java)
                                                                   at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
                                                                   at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:681)
                                                                   at android.os.BinderProxy.transact(<Xposed>)
                                                                   at com.fingerprint.service.IFingerprintService$Stub$Proxy.open(IFingerprintService.java:259)
                                                                   at com.fingerprint.service.FingerprintManager.<init>(FingerprintManager.java:102)
                                                                   at com.fingerprint.service.FingerprintManager.open(FingerprintManager.java:149)
                                                                   at ch.ione.safefingerprint.fingerprint.FingerprintFPCImpl.getIds(FingerprintFPCImpl.java:91)
                                                                   at ch.ione.safefingerprint.fingerprint.FingerprintDelegate.getIds(FingerprintDelegate.java:53)
                                                                   at ch.ione.safefingerprint.service.FingerprintAuthenticationService.getIds(FingerprintAuthenticationService.java:252)
                                                                   at ch.ione.safefingerprint.ui.fragments.ManageFingerprintsFragment.updateFingerprintList(ManageFingerprintsFragment.java:205)
                                                                   at ch.ione.safefingerprint.ui.fragments.ManageFingerprintsFragment.access$100(ManageFingerprintsFragment.java:29)
                                                                   at ch.ione.safefingerprint.ui.fragments.ManageFingerprintsFragment$6.onServiceConnected(ManageFingerprintsFragment.java:118)
                                                                   at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java)
                                                                   at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java)
                                                                   at android.os.Handler.handleCallback(Handler.java)
                                                                   at android.os.Handler.dispatchMessage(Handler.java)
                                                                   at android.os.Looper.loop(Looper.java)
                                                                   at android.app.ActivityThread.main(ActivityThread.java)
                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                   at java.lang.reflect.Method.invoke(Method.java:372)
                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java)
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)
                                                                   at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:117)
                                                                Caused by: com.github.anrwatchdog.ANRError$$$_Thread: FinalizerDaemon
                                                                   at java.lang.Object.wait(Native Method)
                                                                   at java.lang.Object.wait(Object.java:422)
                                                                   at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:101)
                                                                   at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:72)
                                                                   at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:173)
                                                                   at java.lang.Thread.run(Thread.java:818)
                                                                Caused by: com.github.anrwatchdog.ANRError$$$_Thread: FinalizerWatchdogDaemon
                                                                   at java.lang.Object.wait(Native Method)
                                                                   at java.lang.Daemons$FinalizerWatchdogDaemon.waitForObject(Daemons.java:239)
                                                                   at java.lang.Daemons$FinalizerWatchdogDaemon.run(Daemons.java:211)
                                                                   at java.lang.Thread.run(Thread.java:818) 
                                                                Caused by: com.github.anrwatchdog.ANRError$$$_Thread: GCDaemon
                                                                   at java.lang.Object.wait(Native Method)
                                                                   at java.lang.Daemons$GCDaemon.run(Daemons.java:341)
                                                                   at java.lang.Thread.run(Thread.java:818) 
                                                                Caused by: com.github.anrwatchdog.ANRError$$$_Thread: HeapTrimmerDaemon
                                                                   at java.lang.Object.wait(Native Method)
                                                                   at java.lang.Daemons$HeapTrimmerDaemon.run(Daemons.java:310)
                                                                   at java.lang.Thread.run(Thread.java:818) 
                                                                Caused by: com.github.anrwatchdog.ANRError$$$_Thread: ReferenceQueueDaemon
                                                                   at java.lang.Object.wait(Native Method)
                                                                   at java.lang.Daemons$ReferenceQueueDaemon.run(Daemons.java:133)
                                                                   at java.lang.Thread.run(Thread.java:818) 
                                                                Caused by: com.github.anrwatchdog.ANRError$$$_Thread: |ANR-WatchDog|
                                                                   at dalvik.system.VMStack.getThreadStackTrace(Native Method)
                                                                   at java.lang.Thread.getStackTrace(Thread.java:580)
                                                                   at java.lang.Thread.getAllStackTraces(Thread.java:522)
                                                                   at com.github.anrwatchdog.ANRError.New(ANRError.java:80)
                                                                   at com.github.anrwatchdog.ANRWatchDog.run(ANRWatchDog.java:175)
03-07 17:52:44.094 18923-18953/ch.ione.safefingerprint E/ACRA: ACRA failed to capture the error - handing off to native error reporter
                                                               java.lang.RuntimeException: Parcelable encountered IOException writing serializable object (name = com.github.anrwatchdog.ANRError)
                                                                   at android.os.Parcel.writeSerializable(Parcel.java)
                                                                   at android.os.Parcel.writeValue(Parcel.java)
                                                                   at android.os.Parcel.writeArrayMapInternal(Parcel.java)
                                                                   at android.os.BaseBundle.writeToParcelInner(BaseBundle.java)
                                                                   at android.os.Bundle.writeToParcel(Bundle.java)
                                                                   at android.os.Parcel.writeBundle(Parcel.java)
                                                                   at android.content.Intent.writeToParcel(Intent.java)
                                                                   at android.os.Parcel.writeTypedArray(Parcel.java)
                                                                   at android.app.ActivityManagerProxy.getIntentSender(ActivityManagerNative.java)
                                                                   at android.app.PendingIntent.getActivity(PendingIntent.java)
                                                                   at android.app.PendingIntent.getActivity(PendingIntent.java)
                                                                   at org.acra.builder.ReportExecutor.createNotification(ReportExecutor.java:335)
                                                                   at org.acra.builder.ReportExecutor.execute(ReportExecutor.java:196)
                                                                   at org.acra.builder.ReportBuilder.build(ReportBuilder.java:144)
                                                                   at org.acra.ErrorReporter.uncaughtException(ErrorReporter.java:259)
                                                                   at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)
                                                                   at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)
                                                                Caused by: java.io.NotSerializableException: com.github.anrwatchdog.ANRError$$
                                                                   at java.io.ObjectOutputStream.writeNewObject(ObjectOutputStream.java:1344)
                                                                   at java.io.ObjectOutputStream.writeObjectInternal(ObjectOutputStream.java:1651)
                                                                   at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1497)
                                                                   at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1461)
                                                                   at java.io.ObjectOutputStream.writeFieldValues(ObjectOutputStream.java:959)
                                                                   at java.io.ObjectOutputStream.defaultWriteObject(ObjectOutputStream.java:360)
                                                                   at java.io.ObjectOutputStream.writeHierarchy(ObjectOutputStream.java:1054)
                                                                   at java.io.ObjectOutputStream.writeNewObject(ObjectOutputStream.java:1384)
                                                                   at java.io.ObjectOutputStream.writeObjectInternal(ObjectOutputStream.java:1651)
                                                                   at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1497)
                                                                   at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1461)
                                                                   at java.io.ObjectOutputStream.writeFieldValues(ObjectOutputStream.java:959)
                                                                   at java.io.ObjectOutputStream.defaultWriteObject(ObjectOutputStream.java:360)
                                                                   at java.lang.Throwable.writeObject(Throwable.java:436)
                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                   at java.lang.reflect.Method.invoke(Method.java:372)
                                                                   at java.io.ObjectOutputStream.writeHierarchy(ObjectOutputStream.java:1033)
                                                                   at java.io.ObjectOutputStream.writeNewObject(ObjectOutputStream.java:1384)
                                                                   at java.io.ObjectOutputStream.writeObjectInternal(ObjectOutputStream.java:1651)
                                                                   at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1497)
                                                                   at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1461)
                                                                   at java.io.ObjectOutputStream.writeFieldValues(ObjectOutputStream.java:959)
                                                                   at java.io.ObjectOutputStream.defaultWriteObject(ObjectOutputStream.java:360)
                                                                   at java.lang.Throwable.writeObject(Throwable.java:436)
                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                   at java.lang.reflect.Method.invoke(Method.java:372)
                                                                   at java.io.ObjectOutputStream.writeHierarchy(ObjectOutputStream.java:1033)
                                                                   at java.io.ObjectOutputStream.writeNewObject(ObjectOutputStream.java:1384)
                                                                   at java.io.ObjectOutputStream.writeObjectInternal(ObjectOutputStream.java:1651)
                                                                   at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1497)
                                                                   at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1461)
                                                                   at java.io.ObjectOutputStream.writeFieldValues(ObjectOutputStream.java:959)
                                                                   at java.io.ObjectOutputStream.defaultWriteObject(ObjectOutputStream.java:360)
                                                                   at java.lang.Throwable.writeObject(Throwable.java:436)
                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                   at java.lang.reflect.Method.invoke(Method.java:372)
                                                                   at java.io.ObjectOutputStream.writeHierarchy(ObjectOutputStream.java:1033)
                                                                   at java.io.ObjectOutputStream.writeNewObject(ObjectOutputStream.java:1384)
                                                               	at java.io.ObjectOutputStream.writeObjectInternal(
03-07 17:52:44.094 18923-18953/ch.ione.safefingerprint I/ACRA: ACRA is disabled for ch.ione.safefingerprint - forwarding uncaught Exception on to default ExceptionHandler
03-07 17:52:44.095 18923-18953/ch.ione.safefingerprint E/AndroidRuntime: FATAL EXCEPTION: |ANR-WatchDog|
                                                                         Process: ch.ione.safefingerprint, PID: 18923
                                                                         com.github.anrwatchdog.ANRError: Application Not Responding
                                                                         Caused by: com.github.anrwatchdog.ANRError$$$_Thread: main
                                                                             at android.os.BinderProxy.transactNative(Native Method)
                                                                             at android.os.BinderProxy.transact(Binder.java)
                                                                             at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
                                                                             at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:681)
                                                                             at android.os.BinderProxy.transact(<Xposed>)
                                                                             at com.fingerprint.service.IFingerprintService$Stub$Proxy.open(IFingerprintService.java:259)
                                                                             at com.fingerprint.service.FingerprintManager.<init>(FingerprintManager.java:102)
                                                                             at com.fingerprint.service.FingerprintManager.open(FingerprintManager.java:149)
                                                                             at ch.ione.safefingerprint.fingerprint.FingerprintFPCImpl.getIds(FingerprintFPCImpl.java:91)
                                                                             at ch.ione.safefingerprint.fingerprint.FingerprintDelegate.getIds(FingerprintDelegate.java:53)
                                                                             at ch.ione.safefingerprint.service.FingerprintAuthenticationService.getIds(FingerprintAuthenticationService.java:252)
                                                                             at ch.ione.safefingerprint.ui.fragments.ManageFingerprintsFragment.updateFingerprintList(ManageFingerprintsFragment.java:205)
                                                                             at ch.ione.safefingerprint.ui.fragments.ManageFingerprintsFragment.access$100(ManageFingerprintsFragment.java:29)
                                                                             at ch.ione.safefingerprint.ui.fragments.ManageFingerprintsFragment$6.onServiceConnected(ManageFingerprintsFragment.java:118)
                                                                             at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java)
                                                                             at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java)
                                                                             at android.os.Handler.handleCallback(Handler.java)
                                                                             at android.os.Handler.dispatchMessage(Handler.java)
                                                                             at android.os.Looper.loop(Looper.java)
                                                                             at android.app.ActivityThread.main(ActivityThread.java)
                                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                                             at java.lang.reflect.Method.invoke(Method.java:372)
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java)
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)
                                                                             at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:117)
                                                                          Caused by: com.github.anrwatchdog.ANRError$$$_Thread: FinalizerDaemon
                                                                             at java.lang.Object.wait(Native Method)
                                                                             at java.lang.Object.wait(Object.java:422)
                                                                             at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:101)
                                                                             at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:72)
                                                                             at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:173)
                                                                             at java.lang.Thread.run(Thread.java:818)
                                                                          Caused by: com.github.anrwatchdog.ANRError$$$_Thread: FinalizerWatchdogDaemon
                                                                             at java.lang.Object.wait(Native Method)
                                                                             at java.lang.Daemons$FinalizerWatchdogDaemon.waitForObject(Daemons.java:239)
                                                                             at java.lang.Daemons$FinalizerWatchdogDaemon.run(Daemons.java:211)
                                                                             at java.lang.Thread.run(Thread.java:818) 
                                                                          Caused by: com.github.anrwatchdog.ANRError$$$_Thread: GCDaemon
                                                                             at java.lang.Object.wait(Native Method)
                                                                             at java.lang.Daemons$GCDaemon.run(Daemons.java:341)
                                                                             at java.lang.Thread.run(Thread.java:818) 
                                                                          Caused by: com.github.anrwatchdog.ANRError$$$_Thread: HeapTrimmerDaemon
                                                                             at java.lang.Object.wait(Native Method)
                                                                             at java.lang.Daemons$HeapTrimmerDaemon.run(Daemons.java:310)
                                                                             at java.lang.Thread.run(Thread.java:818) 
                                                                          Caused by: com.github.anrwatchdog.ANRError$$$_Thread: ReferenceQueueDaemon
                                                                             at java.lang.Object.wait(Native Method)
                                                                             at java.lang.Daemons$ReferenceQueueDaemon.run(Daemons.java:133)
                                                                             at java.lang.Thread.run(Thread.java:818) 
                                                                          Caused by: com.github.anrwatchdog.ANRError$$$_Thread: |ANR-WatchDog|
                                                                             at dalvik.system.VMStack.getThreadStackTrace(Native Method)
                                                                             at java.lang.Thread.getStackTrace(Thread.java:580)
                                                                             at java.lang.Thread.getAllStackTraces(Thread.java:522)
                                                                             at com.github.anrwatchdog.ANRError.New(ANRError.java:80)
                                                                             at com.github.anrwatchdog.ANRWatchDog.run(ANRWatchDog.java:175)
```

**Comment by SalomonBrys** [comment]
Maybe that's the issue: "ACRA is disabled for ch.ione.safefingerprint" ?

**Comment by rssc** [comment]
Hi, thanks for the reply.

Fair assumption. However, I tested it with a regular NullPointerException, which was caught without problems. My assumption was that it says ACRA is disabled because it couldn't catch the exception, which seems to be the case.
So I think the error still goes back to what it says:

```
Caused by: java.io.NotSerializableException: com.github.anrwatchdog.ANRError$$
```

Adding "implements Serializable" to the static inner class "$" fixes that one, but then I get a serializable error on the anonymous inner class:

```
Caused by: java.io.NotSerializableException: com.github.anrwatchdog.ANRError$1
```

which I don't even know which one it is. Might be this one here:

```
final Map<Thread, StackTraceElement[]> stackTraces = new TreeMap<Thread, StackTraceElement[]>(new Comparator<Thread>() {
...
```
(at least that looks most similar to what decompiling ANRError$1.class gives me).

But I am not familiar enough with the code to fix that one.

Any thoughts?

Thanks!

**Comment by SalomonBrys** [comment]
Well, the exception was not serializable indeed, which makes ACRA crash.
I will publish `v1.2.0` later today that corrects this issue.
Basically, I've stopped attaching the `Map<Thread, StackTraceElement[]>` of running threads / stacktraces to the exception considering that:

 - It's not serializable
 - It can be very easily obtained via `Thread.getAllStackTraces()`
 - I'm pretty sure no one uses it anyway

All stack traces are still visible in the `ANRError` stack trace, so it won't affect reporting.

I will post here as soon as it is available on Maven :)

**Comment by SalomonBrys** [comment]
`v1.2.0` is pushed. The `ANRError` is now serializable (I've checked).
Thanks for the report :)
