### ISSUE TITLE
I am getting anr exception, don't know what is root cause

### ISSUE THREAD

**Issue by amankumarjain** [SalomonBrys/ANR-WatchDog#31]
```
01-25 15:37:59.706 17949-17956/in.codersbyte.namostu I/art: Thread[3,tid=17956,WaitingInMainSignalCatcherLoop,Thread*=0x7fa064f400,peer=0x12c24a60,"Signal Catcher"]: reacting to signal 3
01-25 15:37:59.901 17949-17956/in.codersbyte.namostu I/art: Wrote stack traces to '/data/anr/traces.txt'
01-25 15:37:59.949 17949-18055/in.codersbyte.namostu E/AndroidRuntime: FATAL EXCEPTION: |ANR-WatchDog|
                                                                       Process: in.codersbyte.namostu, PID: 17949
                                                                       com.github.anrwatchdog.ANRError: Application Not Responding
                                                                       Caused by: com.github.anrwatchdog.ANRError$$$_Thread: main (state = RUNNABLE)
                                                                           at android.view.ThreadedRenderer.nSetStopped(Native Method)
                                                                           at android.view.ThreadedRenderer.setStopped(ThreadedRenderer.java:494)
                                                                           at android.view.ViewRootImpl.draw(ViewRootImpl.java:2831)
                                                                           at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2646)
                                                                           at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2253)
                                                                           at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1288)
                                                                           at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6359)
                                                                           at android.view.Choreographer$CallbackRecord.run(Choreographer.java:873)
                                                                           at android.view.Choreographer.doCallbacks(Choreographer.java:685)
                                                                           at android.view.Choreographer.doFrame(Choreographer.java:621)
                                                                           at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:859)
                                                                           at android.os.Handler.handleCallback(Handler.java:754)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                           at android.os.Looper.loop(Looper.java:163)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:6237)
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:877)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
                                                                        Caused by: com.github.anrwatchdog.ANRError$$$_Thread: Answers Events Handler1 (state = TIMED_WAITING)
                                                                           at java.lang.Object.wait(Native Method)
                                                                           at java.lang.Thread.parkFor$(Thread.java:2160)
                                                                           at sun.misc.Unsafe.park(Unsafe.java:325)
                                                                           at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:201)
                                                                           at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2077)
                                                                           at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1103)
                                                                           at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1084)
                                                                           at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1058)
                                                                           at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1118)
                                                                           at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                           at io.fabric.sdk.android.services.common.ExecutorUtils$1$1.onRun(ExecutorUtils.java:75)
                                                                           at io.fabric.sdk.android.services.common.BackgroundPriorityRunnable.run(BackgroundPriorityRunnable.java:30)
                                                                           at java.lang.Thread.run(Thread.java:760)
                                                                        Caused by: com.github.anrwatchdog.ANRError$$$_Thread: AsyncTask #10 (state = TIMED_WAITING)
                                                                           at java.lang.Object.wait(Native Method)
                                                                           at java.lang.Thread.parkFor$(Thread.java:2160)
                                                                           at sun.misc.Unsafe.park(Unsafe.java:325)
                                                                           at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:201)
                                                                           at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2077)
                                                                           at java.util.concurrent.LinkedBlockingQueue.poll(LinkedBlockingQueue.java:438)
                                                                           at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1057)
                                                                           at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1118)
                                                                           at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                           at java.lang.Thread.run(Thread.java:760) 
                                                                        Caused by: com.github.anrwatchdog.ANRError$$$_Thread: AsyncTask #9 (state = TIMED_WAITING)
                                                                           at java.lang.Object.wait(Native Method) 
                                                                           at java.lang.Thread.parkFor$(Thread.java:2160) 
                                                                           at sun.misc.Unsafe.park(Unsafe.java:325) 
                                                                           at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:201) 
                                                                           at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2077) 
                                                                           at java.util.concurrent.LinkedBlockingQueue.poll(LinkedBlockingQueue.java:438) 
                                                                           at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1057) 
                                                                           at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1118) 
                                                                           at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
                                                                           at java.lang.Thread.run(Thread.java:760) 
                                                                        Caused by: com.github.anrwatchdog.ANRError$$$_Thread: Crashlytics Exception Handler1 (state = WAITING)
                                                                           at java.lang.Object.wait(Native Method)
                                                                           at java.lang.Thread.parkFor$(Thread.java:2160)
                                                                           at sun.misc.Unsafe.park(Unsafe.java:325)
                                                                           at java.util.concurrent.locks.LockSupport.park(LockSupport.java:161)
                                                                           at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2035)
                                                                           at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:413)
                                                                           at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1058)
01-25 15:37:59.950 17949-18055/in.codersbyte.namostu E/AndroidRuntime:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1118)
                                                                           at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                           at io.fabric.sdk.android.services.common.ExecutorUtils$1$1.onRun(ExecutorUtils.java:75)
                                                                           at io.fabric.sdk.android.services.common.BackgroundPriorityRunnable.run(BackgroundPriorityRunnable.java:30)
                                                                           	... 1 more
                                                                        Caused by: com.github.anrwatchdog.ANRError$$$_Thread: FileObserver (state = RUNNABLE)
                                                                           at android.os.FileObserver$ObserverThread.observe(Native Method)
                                                                           at android.os.FileObserver$ObserverThread.run(FileObserver.java:85)
                                                                        Caused by: com.github.anrwatchdog.ANRError$$$_Thread: FinalizerDaemon (state = WAITING)
                                                                           at java.lang.Object.wait(Native Method)
                                                                           at java.lang.Object.wait(Object.java:407)
                                                                           at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:188)
                                                                           at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:209)
                                                                           at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:204)
                                                                           at java.lang.Thread.run(Thread.java:760)
                                                                        Caused by: com.github.anrwatchdog.ANRError$$$_Thread: FinalizerWatchdogDaemon (state = WAITING)
                                                                           at java.lang.Object.wait(Native Method)
                                                                           at java.lang.Daemons$FinalizerWatchdogDaemon.sleepUntilNeeded(Daemons.java:269)
                                                                           at java.lang.Daemons$FinalizerWatchdogDaemon.run(Daemons.java:249)
                                                                           at java.lang.Thread.run(Thread.java:760) 
                                                                        Caused by: com.github.anrwatchdog.ANRError$$$_Thread: FrescoDecodeExecutor-1 (state = WAITING)
                                                                           at java.lang.Object.wait(Native Method)
                                                                           at java.lang.Thread.parkFor$(Thread.java:2160)
                                                                           at sun.misc.Unsafe.park(Unsafe.java:325)
                                                                           at java.util.concurrent.locks.LockSupport.park(LockSupport.java:161)
                                                                           at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2035)
                                                                           at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:413)
                                                                           at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1058)
                                                                           at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1118)
                                                                           at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                           at com.facebook.imagepipeline.core.PriorityThreadFactory$1.run(PriorityThreadFactory.java:53)
                                                                           at java.lang.Thread.run(Thread.java:760) 
                                                                        Caused by: com.github.anrwatchdog.ANRError$$$_Thread: FrescoIoBoundExecutor-1 (state = WAITING)
                                                                           at java.lang.Object.wait(Native Method) 
                                                                           at java.lang.Thread.parkFor$(Thread.java:2160) 
                                                                           at sun.misc.Unsafe.park(Unsafe.java:325) 
                                                                           at java.util.concurrent.locks.LockSupport.park(LockSupport.java:161) 
                                                                           at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2035) 
                                                                           at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:413) 
                                                                           at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1058) 
                                                                           at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1118) 
                                                                           at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
                                                                           at com.facebook.imagepipeline.core.PriorityThreadFactory$1.run(PriorityThreadFactory.java:53) 
                                                                           at java.lang.Thread.run(Thread.java:760) 
                                                                        Caused by: com.github.anrwatchdog.ANRError$$$_Thread: FrescoLightWeightBackgroundExecutor-1 (state = WAITING)
                                                                           at java.lang.Object.wait(Native Method) 
                                                                           at java.lang.Thread.parkFor$(Thread.java:2160) 
                                                                           at sun.misc.Unsafe.park(Unsafe.java:325) 
                                                                           at java.util.concurrent.locks.LockSupport.park(LockSupport.java:161) 
                                                                           at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2035) 
                                                                           at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:413) 
                                                                           at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1058) 
                                                                           at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1118) 
                                                                           at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
                                                                           at com.facebook.imagepipeline.core.PriorityThreadFactory$1.run(PriorityThreadFactory.java:53) 
                                                                           at java.lang.Thread.run(Thread.java:760) 
                                                                        Caused by: com.github.anrwatchdog.ANRError$$$_Thread: HeapTaskDaemon (state = BLOCKED)
                                                                           at dalvik.system.VMRuntime.runHeapTasks(Native Method)
                                                                           at java.lang.Daemons$HeapTaskDaemon.run(Daemons.java:433)
                                                                           at java.lang.Thread.run(Thread.java:760) 
                                                                        Caused by: com.github.anrwatchdog.ANRError$$$_Thread: OkHttp ConnectionPool (state = TIMED_WAITING)
                                                                           at java.lang.Object.wait(Native Method)
                                                                           at com.android.okhttp.ConnectionPool.performCleanup(ConnectionPool.java:307)
                                                                           at com.android.okhttp.ConnectionPool.runCleanupUntilPoolIsEmpty(ConnectionPool.java:244)
                                                                           at com.android.okhttp.ConnectionPool.-wrap0(ConnectionPool.java)
                                                                           at com.android.okhttp.ConnectionPool$1.run(ConnectionPool.java:98)
                                                                           at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                           at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                           at java.lang.Thread.run(Thread.java:760) 
                                                                        Caused by: com.github.anrwatchdog.ANRError$$$_Thread: Okio Watchdog (state = WAITING)
                                                                           at java.lang.Object.wait(Native Method)
                                                                           at com.android.okhttp.okio.AsyncTimeout.awaitTimeout(AsyncTimeout.java:311)
                                                                           at com.android.okhttp.okio.AsyncTimeout.-wrap0(AsyncTimeout.java)
                                                                           at com.android.okhttp.okio.AsyncTimeout$Watchdog.run(AsyncTimeout.java:286)
                                                                        Caused by: com.github.anrwatchdog.ANRError$$$_Thread: Queue (state = WAITING)
                                                                           at java.lang.Object.wait(Native Method)
                                                                           at java.lang.Thread.parkFor$(Thread.java:2160)
                                                                           at sun.misc.Unsafe.park(Unsafe.java:325)
                                                                           at java.util.concurrent.locks.LockSupport.park(LockSupport.java:161)
                                                                           at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2035)
01-25 15:37:59.951 17949-18055/in.codersbyte.namostu E/AndroidRuntime:     at java.util.concurrent.PriorityBlockingQueue.take(PriorityBlockingQueue.java:519)
                                                                           at io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.performOperation(DependencyPriorityBlockingQueue.java:197)
                                                                           at io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.get(DependencyPriorityBlockingQueue.java:236)
                                                                           at io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.take(DependencyPriorityBlockingQueue.java:65)
                                                                           at io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.take(DependencyPriorityBlockingQueue.java:46)
                                                                           at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1058)
                                                                           at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1118)
                                                                           at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                           at java.lang.Thread.run(Thread.java:760)
                                                                        Caused by: com.github.anrwatchdog.ANRError$$$_Thread: ReferenceQueueDaemon (state = WAITING)
                                                                           at java.lang.Object.wait(Native Method)
                                                                           at java.lang.Daemons$ReferenceQueueDaemon.run(Daemons.java:150)
                                                                           at java.lang.Thread.run(Thread.java:760) 
                                                                        Caused by: com.github.anrwatchdog.ANRError$$$_Thread: Thread-18 (state = WAITING)
                                                                           at java.lang.Object.wait(Native Method)
                                                                           at java.lang.Thread.parkFor$(Thread.java:2160)
                                                                           at sun.misc.Unsafe.park(Unsafe.java:325)
                                                                           at java.util.concurrent.locks.LockSupport.park(LockSupport.java:161)
                                                                           at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2035)
                                                                           at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:413)
                                                                           at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1058)
                                                                           at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1118)
                                                                           at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                           at java.lang.Thread.run(Thread.java:760) 
                                                                        Caused by: com.github.anrwatchdog.ANRError$$$_Thread: Thread-19 (state = WAITING)
                                                                           at java.lang.Object.wait(Native Method) 
                                                                           at java.lang.Thread.parkFor$(Thread.java:2160) 
                                                                           at sun.misc.Unsafe.park(Unsafe.java:325) 
                                                                           at java.util.concurrent.locks.LockSupport.park(LockSupport.java:161) 
                                                                           at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2035) 
                                                                           at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:413) 
                                                                           at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1058) 
                                                                           at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1118) 
                                                                           at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
                                                                           at java.lang.Thread.run(Thread.java:760) 
                                                                        Caused by: com.github.anrwatchdog.ANRError$$$_Thread: Thread-7 (state = WAITING)
                                                                           at java.lang.Object.wait(Native Method) 
                                                                           at java.lang.Thread.parkFor$(Thread.java:2160) 
                                                                           at sun.misc.Unsafe.park(Unsafe.java:325) 
                                                                           at java.util.concurrent.locks.LockSupport.park(LockSupport.java:161) 
                                                                           at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2035) 
                                                                           at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:413) 
                                                                           at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1058) 
                                                                           at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1118) 
                                                                           at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
                                                                           at java.lang.Thread.run(Thread.java:760) 
                                                                        Caused by: com.github.anrwatchdog.ANRError$$$_Thread: fifo-pool-thread-0 (state = WAITING)
                                                                           at java.lang.Object.wait(Native Method)
                                                                           at java.lang.Thread.parkFor$(Thread.java:2160)
                                                                           at sun.misc.Unsafe.park(Unsafe.java:325)
                                                                           at java.util.concurrent.locks.LockSupport.park(LockSupport.java:161)
                                                                           at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2035)
                                                                           at java.util.concurrent.PriorityBlockingQueue.take(PriorityBlockingQueue.java:519)
                                                                           at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1058)
                                                                           at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1118)
                                                                           at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                           at java.lang.Thread.run(Thread.java:760)
                                                                           at com.bumptech.glide.load.engine.executor.FifoPriorityThreadPoolExecutor$DefaultThreadFactory$1.run(FifoPriorityThreadPoolExecutor.java:118)
                                                                        Caused by: com.github.anrwatchdog.ANRError$$$_Thread: pool-1-thread-1 (state = WAITING)
                                                                           at java.lang.Object.wait(Native Method)
                                                                           at java.lang.Thread.parkFor$(Thread.java:2160)
                                                                           at sun.misc.Unsafe.park(Unsafe.java:325)
                                                                           at java.util.concurrent.locks.LockSupport.park(LockSupport.java:161)
                                                                           at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2035)
                                                                           at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:413)
                                                                           at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1058)
                                                                           at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1118)
                                                                           at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                           at java.lang.Thread.run(Thread.java:760)
                                                                        Caused by: com.github.anrwatchdog.ANRError$$$_Thread: pool-7-thread-1 (state = WAITING)
                                                                           at java.lang.Object.wait(Native Method) 
                                                                           at java.lang.Thread.parkFor$(Thread.java:2160) 
                                                                           at sun.misc.Unsafe.park(Unsafe.java:325) 
                                                                           at java.util.concurrent.locks.LockSupport.park(LockSupport.java:161) 
                                                                           at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2035) 
                                                                           at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:413) 
                                                                           at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1058) 
                                                                           at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1118) 
                                                                           at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
                                                                           at java.lang.Thread.run(Thread.java:760) 
                                                                        Caused by: com.github.anrwatchdog.ANRError$$$_Thread: |ANR-WatchDog| (state = RUNNABLE)
                                                                           at dalvik.system.VMStack.getThreadStackTrace(Native Method)
01-25 15:37:59.952 17949-18055/in.codersbyte.namostu E/AndroidRuntime:     at java.lang.Thread.getStackTrace(Thread.java:1565)
                                                                           at java.lang.Thread.getAllStackTraces(Thread.java:1615)
                                                                           at com.github.anrwatchdog.ANRError.New(ANRError.java:72)
                                                                           at com.github.anrwatchdog.ANRWatchDog.run(ANRWatchDog.java:209)
```

**Comment by SalomonBrys** [comment]
No idea why your app is freezing.
This is not an ANR-Watchdog issue.

**Comment by siyehua** [comment]
I have same case . Anybodody find the root cause?

**Comment by chiragrathipipra** [comment]
i also faced same issue, any findout this error is coming.
